version: '3'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
    labels:
      - traefik.enable=true
      - traefik.http.routers.crypto-wars.rule=Host(`crypto-wars.prod-n8n.omvpb.ovh`)
      - traefik.http.routers.crypto-wars.entrypoints=websecure
      - traefik.http.routers.crypto-wars.tls=true
      - traefik.http.routers.crypto-wars.tls.certresolver=lets-encrypt
      - traefik.http.services.crypto-wars.loadbalancer.server.port=3000
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=********
      - RESEND_API_KEY=********
    networks:
      - hosting_web

  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    restart: always
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_SONIC}
      - CONTRACT_ADDRESS=${NEXT_PUBLIC_SONIC_TESTNET_CONTRACT}
      - RPC='https://rpc.blaze.soniclabs.com'
    networks:
      - hosting_web

  cronberachain:
    build:
      context: .
      dockerfile: Dockerfile.cron
    restart: always
    logging:
      options:
        max-size: '12m'
        max-file: '5'
      driver: json-file
    environment:
      - PRIVATE_KEY=${PRIVATE_KEY_BERACHAIN}
      - CONTRACT_ADDRESS=${NEXT_PUBLIC_BERACHAIN_TESTNET_CONTRACT}
      - RPC='https://bartio.rpc.berachain.com'
    networks:
      - hosting_web

networks:
  hosting_web:
    external:
      name: traefik-proxy